Related to issue #71
acikkaynak/deprem-yardim-backend pull request #73
Opened 2023-02-07 17:59 UTC by KarahanS

issue by @WazeHell

2023-02-07 18:01 UTC, KarahanS commented
Aim is to validate the address by checking whether or not it belongs to one of the cities from the corresponding region.

2023-02-07 18:03 UTC, WazeHell commented
there's typo in "Hatay'"

2023-02-08 00:57 UTC, okankaraduman commented on applications/tweets/helpers.py
> +    allowed_cities = ["Gaziantep", "Malatya", "Batman", "Bingöl", "Elazığ", "Kilis", "Diyarbakır", "Mardin", "Siirt", "Şırnak", "Van", "Muş", "Bitlis", "Hakkari", "Adana", "Osmaniye","Hatay"]
Bunu yapmak yerine aşağıdaki regexi kullanarak uppercase ve typoları da yakalayan bir kurgu yapalım
```suggestion
(?i)((gaz[ıiİI]antep)|(malatya)|(batman)|(b[ıiIİ]ng[oöOÖ]l)|(elaz[Iİıi][gğ])|(kilis)|(diyarbak[ıiIİ]r)|(mardin)|(siirt)|([SsŞş][ıiIİ]rnak)|(van)|(mu[sşSŞ])|(bitlis)|(hakkari)|(adana)|(osmaniye)|(hatay)|(kahramanmara[sşSŞ])|(mara[SŞsş])|(antep))

```

2023-02-08 01:00 UTC, okankaraduman requested changes
comment'e göre değiştirmeliyiz.

2023-02-08 05:42 UTC, KarahanS commented
* Added regex for cities.
* Resolved merge conflict.
You can test the regex using the code below:
```python
import re
allowed_cities = '(?i)((gaz[ıiİI]*antep)|(malatya)|(batman)|(b[ıiIİ]*ng[oöOÖ]*l)|(elaz[Iİıi]*[gğ])|(kilis)|(diyarbak[ıiIİ]*r)|(mardin)|(siirt)|([SsŞş]*[ıiIİ]*rnak)|(van)|(mu[sşSŞ]*)|(bitlis)|(hakkari)|(adana)|(osmaniye)|(hatay)|(kahramanmara[sşSŞ]*)|(mara[SŞsş]*)|(antep))'
allowed_cities_re = re.compile(allowed_cities)
city  = "biingOl"
if re.search(allowed_cities_re, city):
    print("match!")
else:
   print("No match!")
```

2023-02-08 05:45 UTC, KarahanS commented
Invalid as the structure of [helpers](https://github.com/acikkaynak/deprem-yardim-backend/blob/main/applications/tweets/helpers.py) has been changed.

2023-02-08 05:45 UTC, closed without merging